import { Link } from 'react-router-dom';

const Hello = () => {
  return (
    <div className="content">
      <div className="home">
      Below is an illustration of passing a React Bootstrap component. It contains a Badge component and a Button component that have been supplied to the as prop. This finally results in the rendering of a Button component with the same styles as a Badge component.Below is an illustration of passing a React Bootstrap component. It contains a Badge component and a Button component that have been supplied to the as prop. This finally results in the rendering of a Button component with the same styles as a Badge component.Below is an illustration of passing a React Bootstrap component. It contains a Badge component and a Button component that have been supplied to the as prop. This finally results in the rendering of a Button component with the same styles as a Badge component.Below is an illustration of passing a React Bootstrap component. It contains a Badge component and a Button component that have been supplied to the as prop. This finally results in the rendering of a Button component with the same styles as a Badge component.Below is an illustration of passing a React Bootstrap component. It contains a Badge component and a Button component that have been supplied to the as prop. This finally results in the rendering of a Button component with the same styles as a Badge component.Below is an illustration of passing a React Bootstrap component. It contains a Badge component and a Button component that have been supplied to the as prop. This finally results in the rendering of a Button component with the same styles as a Badge component.Below is an illustration of passing a React Bootstrap component. It contains a Badge component and a Button component that have been supplied to the as prop. This finally results in the rendering of a Button component with the same styles as a Badge component.
      Below is an illustration of passing a React Bootstrap component. It contains a Badge component and a Button component that have been supplied to the as prop. This finally results in the rendering of a Button component with the same styles as a Badge component.Below is an illustration of passing a React Bootstrap component. It contains a Badge component and a Button component that have been supplied to the as prop. This finally results in the rendering of a Button component with the same styles as a Badge component.Below is an illustration of passing a React Bootstrap component. It contains a Badge component and a Button component that have been supplied to the as prop. This finally results in the rendering of a Button component with the same styles as a Badge component.Below is an illustration of passing a React Bootstrap component. It contains a Badge component and a Button component that have been supplied to the as prop. This finally results in the rendering of a Button component with the same styles as a Badge component.Below is an illustration of passing a React Bootstrap component. It contains a Badge component and a Button component that have been supplied to the as prop. This finally results in the rendering of a Button component with the same styles as a Badge component.Below is an illustration of passing a React Bootstrap component. It contains a Badge component and a Button component that have been supplied to the as prop. This finally results in the rendering of a Button component with the same styles as a Badge component.Below is an illustration of passing a React Bootstrap component. It contains a Badge component and a Button component that have been supplied to the as prop. This finally results in the rendering of a Button component with the same styles as a Badge component.Below is an illustration of passing a React Bootstrap component. It contains a Badge component and a Button component that have been supplied to the as prop. This finally results in the rendering of a Button component with the same styles as a Badge component.Below is an illustration of passing a React Bootstrap component. It contains a Badge component and a Button component that have been supplied to the as prop. This finally results in the rendering of a Button component with the same styles as a Badge component.Below is an illustration of passing a React Bootstrap component. It contains a Badge component and a Button component that have been supplied to the as prop. This finally results in the rendering of a Button component with the same styles as a Badge component.
      Below is an illustration of passing a React Bootstrap component. It contains a Badge component and a Button component that have been supplied to the as prop. This finally results in the rendering of a Button component with the same styles as a Badge component.Below is an illustration of passing a React Bootstrap component. It contains a Badge component and a Button component that have been supplied to the as prop. This finally results in the rendering of a Button component with the same styles as a Badge component.Below is an illustration of passing a React Bootstrap component. It contains a Badge component and a Button component that have been supplied to the as prop. This finally results in the rendering of a Button component with the same styles as a Badge component.Below is an illustration of passing a React Bootstrap component. It contains a Badge component and a Button component that have been supplied to the as prop. This finally results in the rendering of a Button component with the same styles as a Badge component.
      Below is an illustration of passing a React Bootstrap component. It contains a Badge component and a Button component that have been supplied to the as prop. This finally results in the rendering of a Button component with the same styles as a Badge component.Below is an illustration of passing a React Bootstrap component. It contains a Badge component and a Button component that have been supplied to the as prop. This finally results in the rendering of a Button component with the same styles as a Badge component.Below is an illustration of passing a React Bootstrap component. It contains a Badge component and a Button component that have been supplied to the as prop. This finally results in the rendering of a Button component with the same styles as a Badge component.Below is an illustration of passing a React Bootstrap component. It contains a Badge component and a Button component that have been supplied to the as prop. This finally results in the rendering of a Button component with the same styles as a Badge component.Below is an illustration of passing a React Bootstrap component. It contains a Badge component and a Button component that have been supplied to the as prop. This finally results in the rendering of a Button component with the same styles as a Badge component.
      </div>
    </div>
  );
};

export default Hello;
